dist: trusty
sudo: required

language:
  - cpp

compiler:
  - gcc
  - clang

script:
  # Run build commands
  - mkdir build
  - cd build
  - cmake ..
  - make

# Disable annoying emails

notifications:
  email: false